# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

# workflow 의 이름
name: Test workflow

on:
  push:
    branches: [ "main" ]

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Standard usage
    - uses:  helaili/jekyll-action@2.0.3
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
  build:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository  
      # 소유자는 actions/ 저장소 이름은 checkout @ 사용 가능한 최신 버전은 v3
      - uses: actions/checkout@v3
      # 소유자는 actions/ 저장소 이름은 setup-node @ 사용 가능한 최신 버전은 v3
      - uses: actions/jekyll-build-pages@v1
      - uses: actions/upload-pages-artifact@v1
      - uses: chmod -c -R +rX "$INPUT_PATH" | while read line; do
      - uses: actions/upload-artifact@v3

      # gitfolio 설치 후,
      # 웹사이트를 빌드할 수 있는 지 확인
      - name: install dependencies
        run: |
          npm i gitfolio -g 
          gitfolio build sonah5009
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2

